### ISSUE TITLE
Issue with geckodriver_autoinstaller

### ISSUE THREAD

**Issue by witmul** [hussien-hussien/TinyEarn#1]
Hi!

So i was trying to use your project, but for some reason below error popped up.
When i go to the link (at the very bottom) it redirects me to "Not Found" page.
And after going to [geckodrive ](https://github.com/mozilla/geckodriver/releases/tag/v0.29.1) page- it doesn't have any "v0.29.1-win32.tar.gz" file (as it is mentioned in below link).

I assume auto-installer is calling a file that is not available anymore. Can you please help?

Many thanks!

`---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
C:\Witalij\Programs\Anaconda\envs\3.8.3_ver_py\lib\site-packages\geckodriver_autoinstaller\utils.py in download_geckodriver(cwd)
    174         try:
--> 175             response = urllib.request.urlopen(url)
    176             if response.getcode() != 200:

C:\Witalij\Programs\Anaconda\envs\3.8.3_ver_py\lib\urllib\request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223 

C:\Witalij\Programs\Anaconda\envs\3.8.3_ver_py\lib\urllib\request.py in open(self, fullurl, data, timeout)
    530             meth = getattr(processor, meth_name)
--> 531             response = meth(req, response)
    532 

C:\Witalij\Programs\Anaconda\envs\3.8.3_ver_py\lib\urllib\request.py in http_response(self, request, response)
    639         if not (200 <= code < 300):
--> 640             response = self.parent.error(
    641                 'http', request, response, code, msg, hdrs)

C:\Witalij\Programs\Anaconda\envs\3.8.3_ver_py\lib\urllib\request.py in error(self, proto, *args)
    568             args = (dict, 'default', 'http_error_default') + orig_args
--> 569             return self._call_chain(*args)
    570 

C:\Witalij\Programs\Anaconda\envs\3.8.3_ver_py\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    501             func = getattr(handler, meth_name)
--> 502             result = func(*args)
    503             if result is not None:

C:\Witalij\Programs\Anaconda\envs\3.8.3_ver_py\lib\urllib\request.py in http_error_default(self, req, fp, code, msg, hdrs)
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650 

HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-7-6342d528faef> in <module>
      2 
      3 
----> 4 scraper = ty.TinyEarn()
      5 tsla = scraper.get_earnings('TSLA', start = '04/23/2017', pandas=True, delay=0)

C:\Witalij\Programs\Anaconda\envs\3.8.3_ver_py\lib\site-packages\TinyEarn\TinyEarn.py in __init__(self)
     19     '''
     20     def __init__(self):
---> 21         geckodriver_autoinstaller.install()
     22 
     23     def get_earnings(self, ticker:str, start, end = datetime.date.today(), pandas = True, delay = 1):

C:\Witalij\Programs\Anaconda\envs\3.8.3_ver_py\lib\site-packages\geckodriver_autoinstaller\__init__.py in install(cwd)
     13     :return: The file path of geckodriver
     14     """
---> 15     geckodriver_filepath = utils.download_geckodriver(cwd)
     16     if not geckodriver_filepath:
     17         logging.debug('Can not download geckodriver.')

C:\Witalij\Programs\Anaconda\envs\3.8.3_ver_py\lib\site-packages\geckodriver_autoinstaller\utils.py in download_geckodriver(cwd)
    177                 raise urllib.error.URLError('Not Found')
    178         except urllib.error.URLError:
--> 179             raise RuntimeError(f'Failed to download geckodriver archive: {url}')
    180         archive = BytesIO(response.read())
    181 

RuntimeError: Failed to download geckodriver archive: https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-win32.tar.gz`

**Comment by hussien-hussien** [comment]
Hey Witmul, did you get this figured out? Sorry, I am just seeing this.

**Comment by witmul** [comment]
Hello, sorry for long response. I used another solution. Thanks!
